<?xml version="1.0" encoding="utf-8"?><Database Name="KhachSan" Class="dbQLKhachSanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THANHQUY\SQLEXPRESS;Initial Catalog=KhachSan;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="KhachSanConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="maDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="soLuongDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_SuDungDichVu" Member="SuDungDichVus" ThisKey="maDV" OtherKey="maDV" Type="SuDungDichVu" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="maDoan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="KhachHang_ThuePhong" Member="ThuePhongs" ThisKey="maKH" OtherKey="maKhach" Type="ThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="maLoaiPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLoaiPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="soNguoiToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="maLoaiPhong" OtherKey="maLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="chucVu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="passWord" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ThuePhong" Member="ThuePhongs" ThisKey="maNV" OtherKey="maNV" Type="ThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="maPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoaiPhong" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tenPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Phong_ThuePhong" Member="ThuePhongs" ThisKey="maPhong" OtherKey="maPhong" Type="ThuePhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="maLoaiPhong" OtherKey="maLoaiPhong" Type="LoaiPhong" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SuDungDichVu" Member="SuDungDichVus">
    <Type Name="SuDungDichVu">
      <Column Name="maSDDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="maThue" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thoiGian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="DichVu_SuDungDichVu" Member="DichVu" ThisKey="maDV" OtherKey="maDV" Type="DichVu" IsForeignKey="true" />
      <Association Name="ThuePhong_SuDungDichVu" Member="ThuePhong" ThisKey="maThue" OtherKey="maThue" Type="ThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="maHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maThuePhong" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="thueVAT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="giamGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ThuePhong_ThanhToan" Member="ThuePhong" ThisKey="maThuePhong" OtherKey="maThue" Type="ThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuePhong" Member="ThuePhongs">
    <Type Name="ThuePhong">
      <Column Name="maThue" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPhong" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="maKhach" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayVao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngayRa" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="ThuePhong_SuDungDichVu" Member="SuDungDichVus" ThisKey="maThue" OtherKey="maThue" Type="SuDungDichVu" />
      <Association Name="ThuePhong_ThanhToan" Member="ThanhToans" ThisKey="maThue" OtherKey="maThuePhong" Type="ThanhToan" />
      <Association Name="KhachHang_ThuePhong" Member="KhachHang" ThisKey="maKhach" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_ThuePhong" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_ThuePhong" Member="Phong" ThisKey="maPhong" OtherKey="maPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
</Database>